base_frame_id: base_link
first_map_only: false
global_frame_id: map
gui_publish_rate: 10.0

# -0.044 -2.969 3.129
initial_pose_x: 0.05
initial_pose_y: -3
initial_pose_a: deg(179)


kld_err: 0.05
kld_z: 0.99
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0

laser_max_beams: 720    # <--- default: 30 | Jackal: 720 | RPLIDAR A1: 360


# laser_max_range: 30.0    # <--- default: -1.0
# laser_min_range: 0.1     # <--- default: -1.0
laser_model_type: likelihood_field
laser_sigma_hit: 0.2
laser_z_hit: 0.5
laser_z_max: 0.05
laser_z_rand: 0.5
laser_z_short: 0.05


max_particles: 2000    # <---  default: 5000 | Jackal: 2000

min_particles: 500


# Expected noise in odom's rotation estimate from the rotational component of the robot's motion
odom_alpha1: 5.0    # <--- default: 0.2

# Expected noise in odom's rotation estimate from translational component of the robot's motion
odom_alpha2: 1.0    # <--- default: 0.2



# Expected noise in odom's translation estimate from the translational component of the robot's motion
odom_alpha3: 0.4    # <--- default: 0.2 | Jakal: 0.8

# Expected noise in odom's translation estimate from the rotational component of the robot's motion
odom_alpha4: 0.2    # <--- default: 0.2


# Translation-related noise parameter (only used if model is "omni").
# odom_alpha5: 0.1    # <--- default: 0.1


odom_frame_id: odom
odom_model_type: diff
# receive_map_topic: true    # <--- only in Jackal example
recovery_alpha_fast: 0.1     # <--- default: 0.0
recovery_alpha_slow: 0.0
resample_interval: 1
transform_tolerance: 5.0

# Rotational movement required before performing a filter update.
update_min_a: deg(15)    # <--- default: 0.52 (pi/6)

# Translational movement required before performing a filter update
update_min_d: 0.1      # <--- default: 0.2


use_map_topic: true
