amcl:
    base_frame_id: base_link



    first_map_only: false
    global_frame_id: map
    gui_publish_rate: 10.0
    initial_pose_a: 0.0
    initial_pose_x: 0.0
    initial_pose_y: 0.0



    kld_err: 0.05
    kld_z: 0.99
    laser_lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_beams: 720    # <--- 30
    laser_max_range: 30.0    # <--- -1.0
    laser_min_range: 0.1    # <--- -1.0
    laser_model_type: likelihood_field
    laser_sigma_hit: 0.2
    laser_z_hit: 0.5
    laser_z_max: 0.05
    laser_z_rand: 0.5
    laser_z_short: 0.05
    max_particles: 2000    # <--- 5000
    min_particles: 500
    odom_alpha1: 0.2
    odom_alpha2: 0.2
    odom_alpha3: 0.2    # <--- 0.8
    odom_alpha4: 0.2
    odom_alpha5: 0.1
    odom_frame_id: odom
    odom_model_type: diff
    receive_map_topic: true    # <--- only here
    recovery_alpha_fast: 0.1    # <--- 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    
    
    
    transform_tolerance: 1.0
    update_min_a: 0.314    # <--- 0.5
    update_min_d: 0.1    # <--- 0.2
    use_map_topic: false
